// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Cache struct {
	Provider  string
	Key       string
	Value     []byte
	ExpiresAt string
}

type Carryover struct {
	ID         int64
	Provider   string
	ExternalID string
	Url        string
	Note       string
	CreatedAt  string
	ResolvedAt string
}

type Explanation struct {
	RunID       string
	Provider    string
	ExternalID  string
	Url         string
	Score       int64
	SignalsJson string
	RecordedAt  string
}

type Idempotency struct {
	Key       string
	ClaimedAt string
}
