// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const cacheGet = `-- name: CacheGet :one
SELECT value, expires_at FROM cache
WHERE provider = ? AND key = ?
`

type CacheGetParams struct {
	Provider string
	Key      string
}

type CacheGetRow struct {
	Value     []byte
	ExpiresAt string
}

func (q *Queries) CacheGet(ctx context.Context, arg CacheGetParams) (CacheGetRow, error) {
	row := q.db.QueryRowContext(ctx, cacheGet, arg.Provider, arg.Key)
	var i CacheGetRow
	err := row.Scan(&i.Value, &i.ExpiresAt)
	return i, err
}

const cachePut = `-- name: CachePut :exec

INSERT INTO cache (provider, key, value, expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(provider, key) DO UPDATE SET
    value = excluded.value,
    expires_at = excluded.expires_at
`

type CachePutParams struct {
	Provider  string
	Key       string
	Value     []byte
	ExpiresAt string
}

// Cache --
func (q *Queries) CachePut(ctx context.Context, arg CachePutParams) error {
	_, err := q.db.ExecContext(ctx, cachePut,
		arg.Provider,
		arg.Key,
		arg.Value,
		arg.ExpiresAt,
	)
	return err
}

const cacheVacuum = `-- name: CacheVacuum :execrows
DELETE FROM cache WHERE expires_at < ?
`

func (q *Queries) CacheVacuum(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, cacheVacuum, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const carryoverFindUnresolved = `-- name: CarryoverFindUnresolved :one

SELECT id, provider, external_id, url, note, created_at, resolved_at
FROM carryover
WHERE provider = ? AND external_id = ? AND resolved_at = ''
ORDER BY id ASC
LIMIT 1
`

type CarryoverFindUnresolvedParams struct {
	Provider   string
	ExternalID string
}

// Carryover --
func (q *Queries) CarryoverFindUnresolved(ctx context.Context, arg CarryoverFindUnresolvedParams) (Carryover, error) {
	row := q.db.QueryRowContext(ctx, carryoverFindUnresolved, arg.Provider, arg.ExternalID)
	var i Carryover
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ExternalID,
		&i.Url,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const carryoverInsert = `-- name: CarryoverInsert :exec
INSERT INTO carryover (provider, external_id, url, note, created_at, resolved_at)
VALUES (?, ?, ?, ?, ?, '')
`

type CarryoverInsertParams struct {
	Provider   string
	ExternalID string
	Url        string
	Note       string
	CreatedAt  string
}

func (q *Queries) CarryoverInsert(ctx context.Context, arg CarryoverInsertParams) error {
	_, err := q.db.ExecContext(ctx, carryoverInsert,
		arg.Provider,
		arg.ExternalID,
		arg.Url,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const carryoverList = `-- name: CarryoverList :many
SELECT id, provider, external_id, url, note, created_at, resolved_at
FROM carryover
WHERE resolved_at = ''
ORDER BY created_at ASC
`

func (q *Queries) CarryoverList(ctx context.Context) ([]Carryover, error) {
	rows, err := q.db.QueryContext(ctx, carryoverList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carryover
	for rows.Next() {
		var i Carryover
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ExternalID,
			&i.Url,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carryoverMarkResolved = `-- name: CarryoverMarkResolved :execrows
UPDATE carryover
SET resolved_at = ?
WHERE id = (
    SELECT c.id FROM carryover c
    WHERE c.provider = ? AND c.external_id = ? AND c.resolved_at = ''
    ORDER BY c.id DESC
    LIMIT 1
)
`

type CarryoverMarkResolvedParams struct {
	ResolvedAt string
	Provider   string
	ExternalID string
}

func (q *Queries) CarryoverMarkResolved(ctx context.Context, arg CarryoverMarkResolvedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, carryoverMarkResolved, arg.ResolvedAt, arg.Provider, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const explanationGet = `-- name: ExplanationGet :one
SELECT run_id, provider, external_id, url, score, signals_json, recorded_at
FROM explanation
WHERE provider = ? AND external_id = ?
ORDER BY recorded_at DESC
LIMIT 1
`

type ExplanationGetParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) ExplanationGet(ctx context.Context, arg ExplanationGetParams) (Explanation, error) {
	row := q.db.QueryRowContext(ctx, explanationGet, arg.Provider, arg.ExternalID)
	var i Explanation
	err := row.Scan(
		&i.RunID,
		&i.Provider,
		&i.ExternalID,
		&i.Url,
		&i.Score,
		&i.SignalsJson,
		&i.RecordedAt,
	)
	return i, err
}

const explanationListByRun = `-- name: ExplanationListByRun :many
SELECT run_id, provider, external_id, url, score, signals_json, recorded_at
FROM explanation
WHERE run_id = ?
ORDER BY recorded_at ASC
`

func (q *Queries) ExplanationListByRun(ctx context.Context, runID string) ([]Explanation, error) {
	rows, err := q.db.QueryContext(ctx, explanationListByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Explanation
	for rows.Next() {
		var i Explanation
		if err := rows.Scan(
			&i.RunID,
			&i.Provider,
			&i.ExternalID,
			&i.Url,
			&i.Score,
			&i.SignalsJson,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const explanationPut = `-- name: ExplanationPut :exec

INSERT INTO explanation (run_id, provider, external_id, url, score, signals_json, recorded_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id, provider, external_id) DO UPDATE SET
    url = excluded.url,
    score = excluded.score,
    signals_json = excluded.signals_json,
    recorded_at = excluded.recorded_at
`

type ExplanationPutParams struct {
	RunID       string
	Provider    string
	ExternalID  string
	Url         string
	Score       int64
	SignalsJson string
	RecordedAt  string
}

// Explanation --
func (q *Queries) ExplanationPut(ctx context.Context, arg ExplanationPutParams) error {
	_, err := q.db.ExecContext(ctx, explanationPut,
		arg.RunID,
		arg.Provider,
		arg.ExternalID,
		arg.Url,
		arg.Score,
		arg.SignalsJson,
		arg.RecordedAt,
	)
	return err
}

const idempotencyClaim = `-- name: IdempotencyClaim :execrows

INSERT INTO idempotency (key, claimed_at)
VALUES (?, ?)
ON CONFLICT(key) DO NOTHING
`

type IdempotencyClaimParams struct {
	Key       string
	ClaimedAt string
}

// Idempotency --
func (q *Queries) IdempotencyClaim(ctx context.Context, arg IdempotencyClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, idempotencyClaim, arg.Key, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
